# Server
server.port=8080

# Routes
spring.cloud.gateway.routes[0].id=admin-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1