server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      enabled: true
